services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./FlightSearch.API
    container_name: flightsearch-api
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__Endpoint=redis:6379
    volumes:
      - ./logstack-data:/app/logstack-data

  worker:
    build:
      context: ./FlightSearch.LogstackToRedisWorker
    container_name: flightsearch-worker
    depends_on:
      - redis
    environment:
      - Redis__Endpoint=redis:6379
    volumes:
      - ./logstack-data:/app/logstack-data
      - ./logstack-archive:/app/logstack-archive
